### ISSUE TITLE
Better HookNode Selection

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/hooknode#25]
This will allow a brokernode to determine which hooknodes are "busy" to determine which hooknnode to send a chunk to.

**Comment by AaronVasquez** [comment]
@rfornea @nymd 

What logic did we want for a broker to choose a hooknode?
We originally discussed "reserving" a hooknode, but I think Bruno doesn't want that because of the added latency.

Without a reputation system in place, did we want an intermediary solution?

Conversation form `#development`, Feb 9th

> Bruno Block [7:47 PM]
> pinging the hook might take more latency no?
> don’t forget the way the selection works:
> DB has a reputation column and a ‘last_access’ column

> Bruno Block [7:49 PM]
> but don’t forget that java iri runs almost the whole tangle
> brokers don’t coordinate about hook node status/reputation
> they don’t trust each other
> 

> Aaron Vasquez [7:49 PM]
> a broker will check if its free to make sure it doesnt send to a busy hooknode

> Bruno Block [7:49 PM]
> they would lie to each other if they could
> they’re greedy

> Aaron Vasquez [7:49 PM]
> yeah, thats why we were thinking of pinging the hook
> to see if its busy

> Bruno Block [7:50 PM]
> there is sufficient entropy to make sure a hook node is not overloaded
> broker nodes also poll hook nodes for their average load
> like the one from the uptime bash command
> broker nodes then act on that load as if it were true
> if a hook node slows down too much then it gets punished
> key point is brokers don’t collaborate on hooks nodes
> it’s a decentralized system
> it’s like having miners trust each other for efficiency

**Comment by rfornea** [comment]
The way I have it set up right now, it just selects the hooknode with the oldest "time_of_last_contact" value.  Originally I had  it picking the one with the highest score, but that wasn't working well because it just kept sending everything to the same hooknode if it got too much of a lead on the others.  

I'm wondering if we might want to do something like order the hooknodes by score, and pick the one with the highest score that has a "time_of_last_contact" value that is at least X minutes old.    

Or maybe sometimes we'd want to pick the highest scoring hooknode with the oldest time over X minutes, and sometimes we just want to pick the one with the oldest time, disregarding score.  Would give new hooknodes a chance to get in on the action.

**Comment by AaronVasquez** [comment]
We should have a formula for combining score + time elapsed. Something like 
`selection_score = score * score_weight + time_elapsed_in_seconds * time_weight`

@pandora23 mentioned using a probabilistic selection, where the higher scoring ones have a higher probability of being chosen, but having the highest score doesn't guarantee being chosen.

We can do something simple, like sum all the selection_scores and assign each hooknode to an interval (higher selection_scores have larger intervals), then choose a random number from 0...sum_of_scores to pick the corresponding hooknode.

**Comment by rfornea** [comment]
selection_score = score * score_weight + time_elapsed_in_seconds * time_weight   

I like this, provided score is not weighted too high.  Not sure if we need the interval though?  We could just have a cron task that re-calcs selection score for all the hooknodes every minute, and then re-calc a hooknode's score when it gets chosen to do something, as its time_of_last_contact would be very low.

**Comment by AaronVasquez** [comment]
@rfornea if we make the call in `getNextHooknode` it would add latency. I think it belongs in the cronjob, and we would somehow incorporate those metrics into the `selection_score`
